### Testing Membuat User beserta dengan Profilenya
POST http://localhost:5000/api/v1/users
Content-Type: application/json

{
    "name": "topik",
    "email": "topik@gmail.com",
    "password": "123456789",
    "identity_type": "KTP",
    "identity_number": "321321123",
    "address": "tasikmalaya"
}

### Testing Melihat daftar dari id beserta profilenya
GET http://localhost:5000/api/v1/users/2
Content-Type: application/json

### Testing Melihat semua id beserta profilenya
GET http://localhost:5000/api/v1/users


### Testing Membuat Account
POST http://localhost:5000/api/v1/accounts
Content-Type: application/json

{
    "bank_name": "BRI",
    "bank_account_number": "123456",
    "balance": 1000000,
    "user_id": 1 
}

### Testing melihat daftar Account dari id
GET http://localhost:3000/api/v1/account/1